import type { NextPage } from "next"
import Head from "next/head"
import { MainContent } from "../components/index"
import useLoadContracts from "../hooks/useLoadContracts"
import useWalletData from "../hooks/useWalletData"

const Home: NextPage = () => {
  useWalletData()
  useLoadContracts()

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <MainContent />
    </>
  )
}

export default Home
